### ISSUE TITLE
DB Connection Information

### ISSUE THREAD

**Issue by Blagomir** [leon-anavi/WhoIsInTheLab#9]
DB connection information should not be added to the project's config file. It should be provided by the web server/environment in order for the DevOps to be able to manage databases independently from a developer and migrate to new DB if needed (again, without developer's knowledge).
e.g. get_env('DB_HOST');

**Comment by leon-anavi** [comment]
Hi Blagomir,

Thank you for the valuable feedback. Please, share the source code with the implementation through a GitHub pull request for a review.

Thanks,
Leon

**Comment by leon-anavi** [comment]
Hi Blagomir,

Merged. Thank you for your contribution! 

Best regards,
Leon
